name: Deploy Monkye pages

on:
  push:
    branches: [main]
    paths:
      - examples/monkey-wasm/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Install dev deps
        run: just setup-dev

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Building pages
        run: just build-pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4